# Site settings
title: Matthew Roberts
email: contact@mroberts.me
pgp: http://keyserver.ubuntu.com:11371/pks/lookup?op=get&amp;fingerprint=on&amp;search=0x210E343B4D1B0E10
url: https://mroberts.me
description: "Web Developer and Theatre Technician"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'
  links-hover: '#11505d'

# Footer settings
footer: Matthew Roberts

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: mastodon
    url: https://tiny.tilde.website/@eruraindil
  - title: twitter
    url: https://twitter.com/eruraindil
  - title: instagram
    url: https://www.instagram.com/eruraindil/
  - title: linkedin
    url: https://www.linkedin.com/in/mattdroberts/
  - title: github
    url: https://github.com/eruraindil

# Build settings
markdown: kramdown
permalink: pretty
gems: [jekyll-paginate, jekyll-feed]
paginate: 5
paginate_path: "blog/:num"
exclude: ["static"]
keep_files: ["static"]
